# Generated by Django 4.2.24 on 2025-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="data_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
