# Generated by Django 4.2.24 on 2025-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_alter_entry_data_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="data_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
